### ISSUE TITLE
Issues #3 #6 #7

### ISSUE THREAD

**Issue by yefovar** [arenitss/Proyecto_Final_Analisis_Numerico_Computo_Cientifico#12]
## Mejoras al proyecto

Areas de oportunidad del proyecto

### Paqueteria
- [x] No importar paqueteria que no se usa

### Typo
- [x] Referencia al International Financial Research no funciona correctamente
- [x] Errores gramaticales
- [x] Revisar ligas del reporte, todas deben corresponder a sitios activos
- [x] En actividades por usuario, eliminar la palabra "hardcorear"

### Base de datos
- [x] Explicar las variables a utilizar: unidades, variable dependiente e independiente
- [x] Periodo de cobertura de variables
- [x] Que significa que un registro tengo un desarrollador o no
- [x] Explicacion de por que hay faltantes

### Problema de optimizacion
- [x] Describir claramente cual es el objetivo que se busca resolver usando optimizacion 
- [x] Para matematica en el reporte no es necesaria pero debemos colocar el problema de optimizacion

### Analisis de datos
- [x] Explicar la presencia de tantos outliers
- [x] Se sugiere cambiar la escala para poder visualizar correctamente
- [x] Describir por que vivienda para una sola familia tiene mayor proporcion de incumplimiento
- [x] A que se refiere la frase "muestra positiva aleatoria"

### Modelaje
- [x] Homologar tratamiento de la base durante todo el analisis
- [x] Explicar premisas durante evaluacion de los modelos
- [x] Siempre que se utiliza una grafica, explicarla
- [x] En modeling, referente a "IV" por que no se consideran dos variables
- [x] Claridad en marcos de referencia utilizados; por ejemplo FICO-WOE, LTV-WOE 
- [x] Que resultados esperamos para cada analisis para poder comparar nuestros modelos
- [x] Cual es la prueba de la binomial que estamos considerando
- [x] Que es fit histogram
- [x] La grafica de time-series real fit se deberia ver de esa manera. Nuevamente definir un marco de referencia
- [x] Describir brier score, en donde mas se utiliza
- [x] Por que hacemos dos modelos si la conclusion es similar. Describir mejor el objetivo para ser mas claros en los resultados que se obtendran.
- [x] Que ventajas tiene un modelo respecto al otro

**Comment by yefovar** [comment]
De acuerdo a lo alineado como equipo, les comparto los issues que hemos trabajado recientemente para poder entregar correcamente el proyecto.

**Comment by Eduardo-Moreno** [comment]
He realizado varios cambios al Reporte, lo faltante es revisar con @oaperez3 la parte de referencias para comparar resultados.

**Comment by yefovar** [comment]
Entregable ajustado con marco de referencia, asi como descripcion de modelo 1 y2. Alinear conclusiones y limpiar repositorio.

**Comment by oaperez3** [comment]
Se explica lo siguiente despues de R = 

Base de datos
 Explicar las variables a utilizar: unidades, variable dependiente e independiente
 R= Se explica en el EDA

Periodo de cobertura de variables:
R = 2000 a 2015

 Que significa que un registro tengo un desarrollador o no
R = Que la vivienda la hizo una empresa (como casas GEO).

 Explicacion de por que hay faltantes
R = Así viene la base.

Problema de optimizacion
 Describir claramente cual es el objetivo que se busca resolver usando optimizacion
R = Regresión Logísstica para Probabilidades de Incumplimiento en el tiempo y para Credit Scoring

 Para matematica en el reporte no es necesaria pero debemos colocar el problema de optimizacion
R = Está en utils_pds2.py

Analisis de datos
 Explicar la presencia de tantos outliers.
R = Las bases créditicias por lo regular contienen outlyers, favor de ser más específico.

 Se sugiere cambiar la escala para poder visualizar correctamente
R = Me imagino que es para la gráfica de Credit Scoring, esa no va, ver el repo/notebooks/CREDIT_SCORING.ipynb

 Describir por que vivienda para una sola familia tiene mayor proporcion de incumplimiento
R = No se puede responder, se tendría que hacer un análisis de causalidad con otros datos.

 A que se refiere la frase "muestra positiva aleatoria"
R = Esa, no se

Modelaje
 Homologar tratamiento de la base durante todo el analisis
R =En el repo/notebooks/CREDIT_SCORING.ipynb y repo/notebooks/pds_instancia_aws.ipynb se homolgan las bases y las funciones

 Explicar premisas durante evaluacion de los modelos
R =En el repo/notebooks/CREDIT_SCORING.ipynb y repo/notebooks/pds_instancia_aws.ipynb se homolgan las bases y las funciones se explica cómo se seleccionaron las variables.


 Siempre que se utiliza una grafica, explicarla
R =Ver reporte

 En modeling, referente a "IV" por que no se consideran dos variables
R = por la eurística que se usa en la práctica de tener un IV menor a 0.02. Ver bibliografía

 Claridad en marcos de referencia utilizados; por ejemplo FICO-WOE, LTV-WOE
R = En el repo/notebooks/CREDIT_SCORING.ipynb y repo/notebooks/pds_instancia_aws.ipynb se diferencia el uso.

 Que resultados esperamos para cada analisis para poder comparar nuestros modelos
R = En el repo/notebooks/CREDIT_SCORING.ipynb y repo/notebooks/pds_instancia_aws.ipynb se muestra el cálculo usando los mpetodos vistos en clase y las funciones de python

 Cual es la prueba de la binomial que estamos considerando
R = Se elimina. Ver  repo/notebooks/CREDIT_SCORING.ipynb y repo/notebooks/pds_instancia_aws.ipynb 

 Que es fit histogram
R = Se elimina. Ver  repo/notebooks/CREDIT_SCORING.ipynb y repo/notebooks/pds_instancia_aws.ipynb 

 La grafica de time-series real fit se deberia ver de esa manera. Nuevamente definir un marco de referencia
R = Si. El pico se refiere al momento de la crisis repo/notebooks/pds_instancia_aws.ipynb 
 
Describir brier score, en donde mas se utiliza
R = Se elimina. Ver  repo/notebooks/CREDIT_SCORING.ipynb y repo/notebooks/pds_instancia_aws.ipynb 

 Por que hacemos dos modelos si la conclusion es similar. Describir mejor el objetivo para ser mas claros en los resultados que se obtendran.
R = Se trata de mostrar que el cálculo de probabilidades de incumplimiento para análisis temporales es distinto al que se usa en modelos de credit scoring

**Comment by yefovar** [comment]
Alineacion de equipo para resolver issues en entregable y repositorio.
