### ISSUE TITLE
Segunda version de Comentarios

### ISSUE THREAD

**Issue by yefovar** [arenitss/Proyecto_Final_Analisis_Numerico_Computo_Cientifico#18]
Atender requerimientos despues de la segunda revision del profesor Erick

- [x] Typo en seccion "Datos", para la variable "time" el typo es "deade"
- [x] Typo despues de sus graficos "varaible"
- [x] Typo de dicotómias
- [x] Typo en el titulo "…Introduccion de los componentes princiaples"
- [x] Incoporar en modelo 1 la curva ROC y comparar contra modelo 2
- [x] La instancia es "Instancia EC2" no "S3" (Servicio de almacenamiento)
- [x] En el primer ajuste repetimos la variable no significativa en la explicacion "Retype_CO_orig_tim"
- [x] En el segundo ajuste con pca, hay mas de dos variables no significativas y volvimos a repetir "Retype_CO_orig_tim"
- [x] Agregar conteo de outliers en la gráfica de outliers
- [x] Graficos de caja removiendo algunos outliers para apreciar las cajas
- [x] Incluir problema de optimizacion de PCA
- [x] Seccion de componentes principales no entendi bien la frase de reduccion de dimensionalidad de la variable estado.
- [x] Modeling 2, falta atender nuestro propio comentario "incorporar comentario que es por persona y no por tiempo"
- [x] Cuando usamos WOE solo mencionar por que se esta sobrescribiendo "data_score"
- [x] En las condiciones KKT no es correcto, el tema está en que programen de manera simple

**Comment by yefovar** [comment]
Resolucion parcial de la segunda version de comentarios.

**Comment by Eduardo-Moreno** [comment]
Cerraré el Issue pues se han cumplido todas las tareas en tiempo RECORD! Buen trabajo
