### ISSUE TITLE
Modelo de Regresión Logística para obtención de Probabilidades de incumplimiento en el tiempo.

### ISSUE THREAD

**Issue by arenitss** [arenitss/Proyecto_Final_Analisis_Numerico_Computo_Cientifico#4]
- [x] Selección de Técnica
- [x] Obtención de Parámetros
- [x] Análisis de medidas de validación
- [x] Proyección o estimación

**Comment by Eduardo-Moreno** [comment]
Me asignaré este Issue :)

**Comment by yefovar** [comment]
Se calculó el modelo de regresión logistica con un correcto ajuste a los datos de entrenamiento

**Comment by Eduardo-Moreno** [comment]
El modelling ha sido finalizado
