### ISSUE TITLE
Modelo de Regresión para uso en Credit Scoring (sobre el mapeo de WOEś)

### ISSUE THREAD

**Issue by arenitss** [arenitss/Proyecto_Final_Analisis_Numerico_Computo_Cientifico#5]
- [x] Selección de Técnica
- [x] Obtención de Parámetros
- [x] Análisis de medidas de validación
- [x] Transformación a scorecards

**Comment by yefovar** [comment]
Se realizó la estimación de parámetros del modelo y se está ajustando el entregable para el reporte final

**Comment by Eduardo-Moreno** [comment]
El modelling ha sido finalizado
