### ISSUE TITLE
Puntos a considerar para su proyecto y que olvidé mencionar en la reunión

### ISSUE THREAD

**Issue by palmoreck** [arenitss/Proyecto_Final_Analisis_Numerico_Computo_Cientifico#8]
Hola! @arenitss @Eduardo-Moreno @oaperez3 @yefovar 

Olvidé en la reunión de ayer preguntar/mencionar lo siguiente:

- [x] ¿Tienen algún marco de referencia con el que compararían sus resultados? ¿qué gráficas/estimaciones esperan tener?

- [x] Coloquen la descripción del problema de optimización del PCA. No recuerdo si acordamos que lo programarían pero podrían reutilizar el metodo de deflation que usaron para la práctica 1

(Quise asignar a @oaperez3 también a este issue pero no pude pues no me aparecía dentro de las opciones de Assignees)

Saludos 👋

**Comment by yefovar** [comment]
Se ajustó el marco de referencia dentro de la explicación del notebook.

**Comment by yefovar** [comment]
Realizamos la programacion de la regresion logística tanto con un método de python como con las funciones vistas en clase y el resultado fue idéntico. Estamos trabajando para realizar lo mismo con el deflation :)

**Comment by yefovar** [comment]
Estamos agregando los marcos de referencia al entregable.
Adicionalmente, estamos utilizando la programacion de deflation para PCA de acuerdo a la metodologia del curso.

**Comment by arenitss** [comment]
Entre los marcos de referencia se agregaron comparaciones entre métodos vistos en clases y funciones predeterminadas, esperamos llegar a los mismos resultados.
También se espera que nuestros resultados modelados se aproximen a los empíricos

**Comment by Eduardo-Moreno** [comment]
Los cambios han sido implementados de manera correcta, cerraré el issue
